version: '3.8'
services:
  dev-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test1
      MYSQL_USER: test1
      MYSQL_PASSWORD: test1
      TZ: 'Asia/Tokyo'
    restart: always
    networks:
      - lesson
networks:
  lesson: